Fix: Vue plugin install error
ERROR: [Vue warn]: Plugin has already been applied to target app.

- `.use(router)` is duplicated

ERROR: [Vue warn]: A plugin must either be a function or an object with an "install" function.
https://vuejs.org/guide/reusability/plugins.html

- `webviewBridge` is just imported because the purpose is to add `window.webViewBridge.send` API.
- Vuex does not use `use(Vuex)` in 4 unlike version 3.
  https://vuex.vuejs.org/installation.html
  https://v3.vuex.vuejs.org/installation.html